name = "PatentClassifications"
uuid = "3698127f-10e0-4de2-a324-67cdbbf5dcbc"
authors = ["Jakob Hoffmann <jfb-hoffmann@hotmail.de> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
Dictionaries = "0.3"
ZipFile = "0.9"
DataDeps = "0.7"
CSV = "0.10"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
